development: &default
  adapter: postgresql
  database: blog_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production 

staging:
  <<: *default
  database: blog_staging   