# 00 * * * *    -> Daily at midnight
# */5 * * * *   -> Every 5 minutes
# */20 * * * *  -> Every 20 minutes
# 0 0 * * *     -> Every day at midnight
# 1 0 * * *     -> Every day at 00:01
# 20 0 * * *    -> Every day at 00:20
# 30 0 * * *    -> Every day at 00:30
# 40 0 * * *    -> Every day at 00:40

# Look config/initializers/sidekiq.rb

# Every day at 00:01
#check_course_hosting_date_job:
#  cron: 1 0 * * * Europe/Istanbul
#  class: JobName
#  queue: high_priority