production:
  :concurrency: 3
staging:
  :concurrency: 3
development:
  :concurrency: 25
  :logfile: ./log/sidekiq.log
  :pidfile: ./tmp/pids/sidekiq.pid
  :daemon: true
:queues:
  - default
  - mailers
  - [high_priority, 2]